name: GitHub Contribution Booster

on:
  workflow_dispatch:

jobs:
  boost-contributions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Git User
        run: |
          git config --global user.name "zyxciss"
          git config --global user.email "your-email@example.com"

      - name: Generate Fake Contributions
        run: |
          for i in {1..10}
          do
            echo "Fake commit $i" >> contributions.txt
            git add contributions.txt
            git commit -m "Fake commit $i"
          done

      - name: Push Changes
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/zyxciss/fuzzy-spork.git
          git push origin main
